# Generated by Django 4.1.5 on 2023-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, unique=True), max_length=255),
        ),
    ]
