# Generated by Django 4.1.3 on 2022-12-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
