# Generated by Django 4.1.5 on 2023-01-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
