# Generated by Django 4.1.5 on 2023-01-03 22:36

import ListItems.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=ListItems.models.ModifiedArrayField(base_field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=50), blank=True, null=True, size=None),
        ),
    ]
