# Generated by Django 4.1.5 on 2023-01-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0007_alter_product_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
