# Generated by Django 4.1.5 on 2023-01-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0008_recommendation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
