# Generated by Django 4.1.5 on 2023-01-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0009_alter_recommendation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
