# Generated by Django 4.1.5 on 2023-01-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0010_recommendation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=5),
        ),
    ]
