version: "3.9"
services:
  shopApp:
    depends_on:
      - postgres_db
    build:
      context: ./shopApp
      dockerfile: Dockerfile
    image: shopapp:1.0.0
    environment:
      - PORT=8001
    env_file:
      - shopApp/.env
    ports:
      - "8001:8001"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - static_files:/app/static
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - shopApp/.env
    command:
      -p 5433
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  static_files:
  postgres_data:
