version: "3.9"
services:
  shopApp:
    depends_on:
      - postgres_db
    build:
      context: ./shopApp
      dockerfile: Dockerfile
    image: shopapp:1.0.0
    environment:
      - PORT=8000
    env_file:
      - shopApp/.env
    ports:
      - "8000:8000"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
    volumes:
      - ./shopApp:/app/
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - shopApp/.env
    command:
      -p 5432
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#  redis_db:
#    image: redis
#    restart: always
#    expose:
#      - 6380
#    ports:
#      - "6380:6380"
#    volumes:
#      - redis_data:/data
#    entrypoint: redis-server --appendonly yes --port 6380

#
volumes:
#  shopApp/:
  postgres_data:
#  redis_data:
