# Generated by Django 4.1.3 on 2023-01-10 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_remove_profile_bio_profile_address_profile_city_and_more'),
        ('ListItems', '0011_recommendation_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('transport_method', models.CharField(choices=[('Courier delivery', 'Courier Delivery'), ('Parcel Post', 'Parcel Post')], default='Courier delivery', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListItems.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.order')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.profile')),
            ],
        ),
    ]
