# Generated by Django 4.1.5 on 2023-01-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_profile_bio_profile_address_profile_city_and_more'),
        ('ListItems', '0011_recommendation_rating'),
        ('ShoppingCart', '0002_alter_shoppingcart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transport_method',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.shoppingcart'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ListItems.product'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='transport_method',
            field=models.CharField(choices=[('Courier delivery', 'Courier Delivery'), ('Parcel Post', 'Parcel Post')], default='Courier delivery', max_length=50),
        ),
    ]
