# Generated by Django 4.1.5 on 2023-01-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_profile_bio_profile_address_profile_city_and_more'),
        ('ListItems', '0011_recommendation_rating'),
        ('ShoppingCart', '0003_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default='1')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ListItems.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='transport_method',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.profile'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='productincart',
            name='shopping_cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.shoppingcart'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.shoppingcart'),
        ),
    ]
