# Generated by Django 4.1.5 on 2023-01-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0004_orderdetails_productincart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
    ]
