# Generated by Django 4.1.5 on 2023-01-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0006_alter_orderdetail_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='product_size',
            field=models.CharField(default='', max_length=1),
        ),
    ]
