# Generated by Django 4.1.3 on 2023-01-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0011_recommendation_rating'),
        ('ShoppingCart', '0007_productincart_product_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together={('product', 'quantity')},
        ),
    ]
