# Generated by Django 4.1.5 on 2023-01-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListItems', '0011_recommendation_rating'),
        ('ShoppingCart', '0008_alter_productincart_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productincart',
            unique_together={('product', 'product_size')},
        ),
    ]
