# Generated by Django 4.1.3 on 2023-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0009_alter_productincart_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=255)),
                ('discount_percent', models.FloatField(max_length=5)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
