# Generated by Django 4.1.3 on 2023-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0010_discountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='shopping_cart_id',
        ),
        migrations.AddField(
            model_name='productincart',
            name='shopping_cart_id',
            field=models.ManyToManyField(to='ShoppingCart.shoppingcart'),
        ),
    ]
