# Generated by Django 4.1.3 on 2023-01-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0011_remove_productincart_shopping_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='shopping_cart_id',
        ),
        migrations.AddField(
            model_name='productincart',
            name='shopping_cart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.shoppingcart'),
        ),
    ]
