# Generated by Django 4.1.3 on 2022-12-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
